name = "Raku Infra Team"
description = "Deployed by Raku Infra Team to handle Raku Doc builds."

host = "127.0.0.1"
port = 10337

[raku-doc]
name = "Raku Doc"
description = "build raku-doc on push event"

# https://docs.github.com/en/webhooks-and-events/webhooks/securing-your-webhooks
secret-token = ""
